appId: YSoftwareRepo.template-electron-cra
productName: template-electron-cra

asar: true

directories:
    buildResources: assets/
    output: release/

files:
    - ./build/**/*
    - ./package.json

dmg:
    contents:
        - type: link
          path: /Applications
          x: 410
          y: 150
        - type: file
          x: 130
          y: 150

mac:
    target: dmg
    category: public.app-category.tools

win:
    target: nsis

nsis:
    oneClick: false
    allowElevation: true
    allowToChangeInstallationDirectory: true

linux:
    target:
        - deb
        - AppImage
