name: Build

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup node modules
              run: npm ci

            - name: Build project
              run: npm run build
