name: Build Release

on:
  push:
    branches: main
    tags: v*.*.*

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate installer
        run: npm run gen-installer

      - name: Upload release to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.YSOFTWAREREPO_GITHUB_TOKEN }}
        with:
          draft: true
          files: release/*.exe
