name: Lint

on:
  push:
    branches:
    - '**'


jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Setup node modules
      run: yarn install

    - name: Lint Main
      run: yarn lint:main

    - name: Lint Renderer ReactApp
      run: yarn lint:renderer:reactapp

    - name: Lint Renderer Root
      run: yarn lint:renderer:root

    - name: Lint Renderer Utils
      run: yarn lint:renderer:utils

    - name: Lint Shared
      run: yarn lint:shared
