name: Lint

on:
  push:
    branches:
    - '**'


jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Setup node modules
      run: yarn install

  lint-main:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Lint Main
      run: yarn lint:main

  lint-renderer-reactapp:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Lint Renderer ReactApp
      run: yarn lint:renderer:reactapp

  lint-renderer-root:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Lint Renderer Root
      run: yarn lint:renderer:root

  lint-renderer-utils:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Lint Renderer Utils
      run: yarn lint:renderer:utils

  lint-shared:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Lint Shared
      run: yarn lint:shared
