name: Lint-Verbose

on:
  push:
    branches:
      - main


jobs:
  lint-main:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: yarn install

      - name: Lint Main
        run: yarn lint:main

  lint-renderer-reactapp:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: yarn install

      - name: Lint Renderer ReactApp
        run: yarn lint:renderer:reactapp

  lint-renderer-root:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: yarn install

      - name: Lint Renderer Root
        run: yarn lint:renderer:root

  lint-renderer-utils:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: yarn install

      - name: Lint Renderer Utils
        run: yarn lint:renderer:utils

  lint-shared:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup node modules
        run: yarn install

      - name: Lint Shared
        run: yarn lint:shared
