name: Release

on:
  push:
    branches:
      - main
      - main-test
      - ci
      - ci-test
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup node modules
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate installer
        run: npm run gen-installer

      - name: Upload release to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.YSOFTWAREREPO_GITHUB_TOKEN }}
        with:
          draft: true
          files: release/*.exe
